# Создаем диск для Wordpress
# ReadWriteMany обычно не используется для hostPath, но возможность подключить этот тип все же есть
# Иногда может понадобится запись нескольким PODs, расположенных на ноде. В задании такой случай. Это нужно использовать с осторожностью
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-storage
  labels:
    app: wordpress
    tier: frontend
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/html"
    type: DirectoryOrCreate
