# Пароль БД будет находиться в secret-объекте
# Текст секрета закодирован по 64-основанию
# Чтобы создать используй `echo -n test | base64`
# Чтобы раскодировать используй `echo dGVzdA== | base64 -d`
# По заданию нам нужен пароль `test2` для пользователя `vova`
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  root-password: dGVzdA==
  user-password: dGVzdDI=

---
# Сразу создадим данные для имени пользователя
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-user
data:
  username: vova
