# Здесь находится сама БД MySQL
# Для сетапа в 1 реплику вполне подходит Deployment, и именно это требуется в задании
# Если требуется настройка с более сложной логикой, обратиcь к StatefulSets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: bitnami/mariadb
        name: mysql
        env:
        - name: BITNAMI_DEBUG
          value: "true"
        - name: MARIADB_DATABASE
          value: challenge
        - name: MARIADB_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-user
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: user-password
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: root-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-persistent-storage
