# По заданию нам требуется часть конфигурационных данных положить прямо в Deployment, часть в ConfigMap, часть в Secret
---
apiVersion: v1
kind: Secret
metadata:
  name: lychee-pass
type: Opaque
data:
  db-name: bHljaGVl # lychee
  root-password: bWFubmFiYWQtZGFiYWQ= # mannabad-dabad
  user-name: bHljaGVldXNlcg== # lycheeuser
  user-password: ZGJwYXNzd29yZA== # dbpassword
---
# Сразу создадим данные для имени пользователя
apiVersion: v1
kind: ConfigMap
metadata:
  name: lychee-settings
data:
  PGID: "1000"
  PUID: "1000"
  TZ: Europe/London
