# Чтобы запустить подготовленные экземпляры в режиме кластера, используй это команду
# Обрати внимание, что PODs с Redis выбираются по метке `-l app=redis-cluster`, возможно у тебя будут другие

kubectl exec -it redis-cluster-0 -- redis-cli --cluster create --cluster-replicas 1 $(kubectl get pods -l app=redis-cluster -o jsonpath='{range.items[*]}{.status.podIP}:6379 ' | sed 's/[[:space:]]:6379//g')
