# Обрати внимание, что диск помечен как tier: frontend
# Это убирает возможность перепутать PVs при bound
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
  labels:
    tier: frontend
spec:
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce
  capacity:
    storage: 300Mi
  hostPath:
    path: /drupal-data
    type: DirectoryOrCreate
