# Для MySQL объявим переменные, требующиеся для создания экземпляра базы
# В Drupal мы их добавим через UI в браузере
---
apiVersion: v1
kind: Secret
metadata:
  name: drupal-mysql-secret
data:
  MYSQL_DATABASE: Y2hhbGxlbmdl  # challenge
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNz  # root_pass
  MYSQL_USER: YWxlbmE=  # alena
  MYSQL_PASSWORD: Ym9tYmFyZGE=  # bombarda
type: Opaque
